var annotated =
[
    [ "atomicunits", "classatomicunits.html", "classatomicunits" ],
    [ "bilinear_class", "classbilinear__class.html", "classbilinear__class" ],
    [ "classical_class", "classclassical__class.html", "classclassical__class" ],
    [ "coupling_class", "classcoupling__class.html", "classcoupling__class" ],
    [ "dipoles_class", "classdipoles__class.html", "classdipoles__class" ],
    [ "errorlog", "classerrorlog.html", "classerrorlog" ],
    [ "filemanager", "classfilemanager.html", "classfilemanager" ],
    [ "fitxydata", "classfitxydata.html", "classfitxydata" ],
    [ "harmonicbath_class", "classharmonicbath__class.html", "classharmonicbath__class" ],
    [ "hb_class", "classhb__class.html", "classhb__class" ],
    [ "hc_class", "classhc__class.html", "classhc__class" ],
    [ "hs_class", "classhs__class.html", "classhs__class" ],
    [ "math", "classmath.html", "classmath" ],
    [ "molreader", "classmolreader.html", "classmolreader" ],
    [ "mpiframework", "classmpiframework.html", "classmpiframework" ],
    [ "outputdisplay", "classoutputdisplay.html", "classoutputdisplay" ],
    [ "pldm_class", "classpldm__class.html", "classpldm__class" ],
    [ "quantum_class", "classquantum__class.html", "classquantum__class" ],
    [ "rand", "classrand.html", "classrand" ],
    [ "spectrometer_class", "classspectrometer__class.html", "classspectrometer__class" ],
    [ "string", "classstring.html", "classstring" ],
    [ "template_class", "classtemplate__class.html", "classtemplate__class" ],
    [ "textgraphs", "classtextgraphs.html", "classtextgraphs" ],
    [ "type_kinds", "classtype__kinds.html", "classtype__kinds" ],
    [ "wallclock", "classwallclock.html", "classwallclock" ]
];