var namespaces =
[
    [ "atomicunits", "namespaceatomicunits.html", null ],
    [ "bilinear_class", "namespacebilinear__class.html", null ],
    [ "classical_class", "namespaceclassical__class.html", null ],
    [ "coupling_class", "namespacecoupling__class.html", null ],
    [ "dipoles_class", "namespacedipoles__class.html", null ],
    [ "errorlog", "namespaceerrorlog.html", null ],
    [ "filemanager", "namespacefilemanager.html", null ],
    [ "fitxydata", "namespacefitxydata.html", null ],
    [ "harmonicbath_class", "namespaceharmonicbath__class.html", null ],
    [ "hb_class", "namespacehb__class.html", null ],
    [ "hc_class", "namespacehc__class.html", null ],
    [ "hs_class", "namespacehs__class.html", null ],
    [ "math", "namespacemath.html", null ],
    [ "molreader", "namespacemolreader.html", null ],
    [ "mpiframework", "namespacempiframework.html", null ],
    [ "outputdisplay", "namespaceoutputdisplay.html", null ],
    [ "pldm_class", "namespacepldm__class.html", null ],
    [ "quantum_class", "namespacequantum__class.html", null ],
    [ "rand", "namespacerand.html", null ],
    [ "spectrometer_class", "namespacespectrometer__class.html", null ],
    [ "string", "namespacestring.html", null ],
    [ "template_class", "namespacetemplate__class.html", null ],
    [ "textgraphs", "namespacetextgraphs.html", null ],
    [ "type_kinds", "namespacetype__kinds.html", null ],
    [ "wallclock", "namespacewallclock.html", null ]
];